### ISSUE TITLE
add a .open method that yields and ensures the journal is closed

### ISSUE THREAD

**Issue by grosser** [ledbettj/systemd-journal#82]
it's easy to forget closing the journal, so how about making it easier to not do that, just like ruby had `File.open do` ?

@ledbettj

**Comment by ledbettj** [comment]
The original design I implemented was to auto-close the file when it was garbage collected via the `ObjectSpace.define_finalizer` method.  It turns out maybe that wasn't the best approach as I think we've seen several problems/bugs where maybe thing's dont get GCed when expected.

So I think this is probably a good idea; expect the user to `close` the journal, provide a method to `close` it automatically (your block suggestion) and retain the finalizer in case the journal is never actually closed explicitly as a safety net.

**Comment by ledbettj** [comment]
Published 1.4.0
