### ISSUE TITLE
Trusted Fields not Returned when Reading Journal

### ISSUE THREAD

**Issue by obokaiwele** [ledbettj/systemd-journal#86]
Example
```ruby
#!/usr/bin/env ruby
require 'systemd/journal'

Systemd::Journal.open(files: ARGV) { |journal|
    journal.each { |entry|
            puts entry.fields
            break
    }
}
```

Returns
```bash
_source_monotonic_timestamp
_transport
priority
syslog_facility
syslog_identifier
message
_boot_id
_machine_id
_hostname
```

Fields that start with double underscore `__` are not returned
- __CURSOR
- __REALTIME_TIMESTAMP
- __MONOTONIC_TIMESTAMP

**Comment by ledbettj** [comment]
Hi!

Those fields are special in that they are not stored as part of the actual journal fields;  there's a separate API call needed to retrieve them.

You can get the timestamps from the `JournalEntry` object directly via `.realtime_timestamp` and friends:  https://github.com/ledbettj/systemd-journal/blob/master/lib/systemd/journal_entry.rb#L27-L40

The cursor is also a special field that is used for navigating the journal.  In order to retrieve that you can access it via the main Journal object.

```
#!/usr/bin/env ruby
require 'systemd/journal'

j = Systemd::Journal.new
entry = j.first
puts entry.fields
puts entry.realtime_timestamp
puts j.cursor
```

Hope this helps!  If there is documentation improvements or API improvements that you'd like to see please let me know or open a PR.
